# Generated by Django 4.0.3 on 2022-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categorie',
            field=models.CharField(choices=[('F', 'Food'), ('H', 'Health'), ('T', 'Transport'), ('E', 'Education'), ('L', 'Leisure'), ('O', 'Others')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
