# Generated by Django 4.0.2 on 2022-02-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['data'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ['data'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
        migrations.AlterModelTable(
            name='despesa',
            table='despesa',
        ),
        migrations.AlterModelTable(
            name='receita',
            table='receita',
        ),
    ]
