# Generated by Django 4.0.2 on 2022-02-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_despesa_options_alter_receita_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'db_table': 'categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['data', 'valor'], 'verbose_name': 'Despesa'},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ['data', 'valor'], 'verbose_name': 'Receita'},
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.categoria'),
            preserve_default=False,
        ),
    ]
