# Generated by Django 4.0.2 on 2022-02-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_categoria_alter_despesa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='financas.categoria'),
        ),
    ]
